### ISSUE TITLE
[Level Zero] Unit_hipMemcpyAsync_hipMultiMemcpyMultiThread sometimes fails

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#127]
Doesn't happen very often

Iris backtrace#1:
```
(gdb) bt
#0  0x00007ffff6475cdb in raise () from /lib64/libc.so.6
#1  0x00007ffff6477375 in abort () from /lib64/libc.so.6
#2  0x00007ffff64bbb07 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff64c3b8a in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff64c45ec in malloc_consolidate () from /lib64/libc.so.6
#5  0x00007ffff64c6bf0 in _int_malloc () from /lib64/libc.so.6
#6  0x00007ffff64c8638 in malloc () from /lib64/libc.so.6
#7  0x00007ffff70538d5 in operator new (sz=1016) at /dev/shm/spack-stage-servesh/spack-stage-gcc-10.2.0-yudlyezca7twgd5o3wkkraur7wdbngdn/spack-src/libstdc++-v3/libsupc++/new_op.cc:50
#8  0x00007ffff5763533 in L0::CommandList::Allocator<L0::CommandListProductFamily<(PRODUCT_FAMILY)18> >::allocate(unsigned int) () from /soft/libraries/intel-gpu-umd/f81b779-2022.06.09/driver/lib64/libze_intel_gpu.so.1
#9  0x00007ffff579fe2b in L0::CommandList::create(unsigned int, L0::Device*, NEO::EngineGroupType, unsigned int, _ze_result_t&) () from /soft/libraries/intel-gpu-umd/f81b779-2022.06.09/driver/lib64/libze_intel_gpu.so.1
#10 0x00007ffff57a8ab8 in L0::DeviceImp::createCommandList(_ze_command_list_desc_t const*, _ze_command_list_handle_t**) () from /soft/libraries/intel-gpu-umd/f81b779-2022.06.09/driver/lib64/libze_intel_gpu.so.1
#11 0x00007ffff789797c in CHIPQueueLevel0::getCmdListCompute (this=this@entry=0xc3ce10) at /home/pvelesko/space/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:717
#12 0x00007ffff78a2391 in CHIPQueueLevel0::enqueueBarrierImpl (this=0xc3ce10, EventsToWaitFor=<optimized out>) at /home/pvelesko/space/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:1121
#13 0x00007ffff782f2f8 in CHIPContext::syncQueues (this=<optimized out>, TargetQueue=0x2) at /home/pvelesko/space/CHIP-SPV/src/CHIPBackend.cc:1009
#14 0x00007ffff7828222 in CHIPQueue::memCopyAsync (this=0xc3ce10, Dst=0xffffd556aa7b0000, Src=0x0, Size=140737325259995) at /home/pvelesko/space/CHIP-SPV/src/CHIPBackend.cc:1471
#15 0x00007ffff784ff94 in hipMemcpyAsync (Dst=0xffffd556aa7b0000, Src=0xffffd556aa7d0000, SizeBytes=131072, Kind=hipMemcpyDeviceToDevice, Stream=0x0) at /home/pvelesko/space/CHIP-SPV/src/CHIPBindings.cc:2075
#16 0x0000000000448c39 in Thread_func<int> (A_d=0xffffd556aa7d0000, B_d=0x2, C_d=<optimized out>, C_h=<optimized out>, Nbytes=131072, mystream=0xc3ce10) at /home/pvelesko/space/CHIP-SPV/HIP/tests/catch/unit/memory/hipMemcpyAsync.cc:54
#17 0x00007ffff707c4f0 in std::execute_native_thread_routine (__p=0xdef1d0) at /dev/shm/spack-stage-servesh/spack-stage-gcc-10.2.0-yudlyezca7twgd5o3wkkraur7wdbngdn/spack-src/libstdc++-v3/src/c++11/thread.cc:80
#18 0x00007ffff682a6ea in start_thread () from /lib64/libpthread.so.0
#19 0x00007ffff6542a8f in clone () from /lib64/libc.so.6
```

Iris backtracke#2:
```
Thread 261 "hipMemcpyAsync" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffe64748700 (LWP 27413)]
0x00007ffff6475cdb in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6475cdb in raise () from /lib64/libc.so.6
#1  0x00007ffff6477375 in abort () from /lib64/libc.so.6
#2  0x00007ffff64bbb07 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff64c3b8a in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff64c5764 in _int_free () from /lib64/libc.so.6
#5  0x00007ffff64c8c8b in __malloc_arena_thread_freeres () from /lib64/libc.so.6
#6  0x00007ffff682a70f in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff6542a8f in clone () from /lib64/libc.so.6
```

Arcticus backtrace#1:
```
#0  0x00007ffff64c6c80 in __malloc_arena_thread_freeres () from /lib64/libc.so.6
#1  0x00007ffff682870f in start_thread () from /lib64/libpthread.so.0
#2  0x00007ffff6540a8f in clone () from /lib64/libc.so.6
```

**Comment by pvelesko** [comment]
Since one of the traces shows failure at command list allocation, implement command list recycling then try again
