### ISSUE TITLE
Failing unit tests when using clang15

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#139]
```
Unit_hipTextureFetch_vector
hipTextureObj2D
hipTextureObj1DFetch
hipTex1DFetchCheckModes
hipNormalizedCoords
hipNormalizedFloat
hipTextureObj1D
hipAddressingModes
```

**Comment by pvelesko** [comment]
@pjaaskel @franz

**Comment by pvelesko** [comment]
the texture tests fail when setting arguments:

```
Thread 1 "hipTex1DFetchCh" received signal SIGSEGV, Segmentation fault.
bt
0x00007ffff7b50383 in __GNU_EH_FRAME_HDR () from /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/build/libCHIP.so
(gdb) bt
#0  0x00007ffff7b50383 in __GNU_EH_FRAME_HDR () from /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/build/libCHIP.so
#1  0x00007fffffff6740 in ?? ()
#2  0x0000555556b09600 in ?? ()
#3  0x00007ffff392adb3 in ?? () from /soft/restricted/CNDA/emb/libraries/intel-level-zero/compute-runtime/20220711.1/lib64/libze_intel_gpu.so.1
#4  0x00007ffff7b23bb2 in CHIPExecItem::setupAllArgs (this=0x7fffffff8388) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:2074
#5  0x00007ffff7b22c60 in CHIPQueueLevel0::launchImpl (this=0x5555560b9bb0, ExecItem=0x7fffffff8388) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/backend/Level0/CHIPBackendLevel0.cc:936
#6  0x00007ffff7a65ab5 in CHIPQueue::launch (this=0x5555560b9bb0, ExecItem=0x7fffffff8388) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPBackend.cc:1670
#7  0x00007ffff7a662c2 in CHIPQueue::launchHostFunc (this=0x5555560b9bb0, HostFunction=0x555555759d58 <tex1dKernel(float*, __hip_texture*)>, NumBlocks=..., DimBlocks=..., Args=0x7fffffff8720, SharedMemBytes=0)
    at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPBackend.cc:1723
#8  0x00007ffff7ab9ccc in hipLaunchKernel (HostFunction=0x555555759d58 <tex1dKernel(float*, __hip_texture*)>, GridDim=..., BlockDim=..., Args=0x7fffffff8720, SharedMem=0, Stream=0x5555560b9bb0)
    at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPBindings.cc:2848
#9  0x0000555555555054 in __device_stub__tex1dKernel(float*, __hip_texture*) ()
#10 0x000055555555574a in runTest (AddressMode=hipAddressModeClamp, FilterMode=hipFilterModePoint) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/samples/texture/hipTex1DFetchCheckModes.cpp:94
#11 0x0000555555555082 in main (argc=1, argv=0x7fffffff8aa8) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/samples/texture/hipTex1DFetchCheckModes.cpp:41
```

**Comment by linehill** [comment]
It could be related to this issue which has been fixed: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/1562. Your llvm-spirv could be outdated.

On my machine the tests passes on intel-compute-runtime 22.35.24055 and the latest revision of LLVM15 and llvm-spirv.

**Comment by pvelesko** [comment]
@linehill  that was it. Thanks.
