### ISSUE TITLE
OpenCL segfault on uninit

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#288]
```
Thread 1 "hipHostMalloc" received signal SIGSEGV, Segmentation fault.
0x00000000000000c1 in ?? ()
(gdb) bt
#0  0x00000000000000c1 in ?? ()
#1  0x00007ffff79fece0 in CHIPBackend::~CHIPBackend (this=0x55555592dea0) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPBackend.cc:1219
#2  0x00007ffff7ab40b5 in CHIPBackendOpenCL::~CHIPBackendOpenCL (this=0x55555592dea0) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/backend/OpenCL/CHIPBackendOpenCL.hh:282
#3  0x00007ffff7ab40d9 in CHIPBackendOpenCL::~CHIPBackendOpenCL (this=0x55555592dea0) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/backend/OpenCL/CHIPBackendOpenCL.hh:282
#4  0x00007ffff79eecd7 in CHIPUninitializeCallOnce () at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPDriver.cc:168
#5  0x00007ffff79f1e32 in std::__invoke_impl<void, void (*)()> (__f=@0x7fffffffc568: 0x7ffff79eec80 <CHIPUninitializeCallOnce()>) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/invoke.h:60
#6  0x00007ffff79f1e15 in std::__invoke<void (*)()> (__fn=@0x7fffffffc568: 0x7ffff79eec80 <CHIPUninitializeCallOnce()>) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/bits/invoke.h:95
#7  0x00007ffff79f1df8 in std::call_once<void (*)()>(std::once_flag&, void (*&&)())::{lambda()#1}::operator()() const (this=0x7fffffffc538) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/mutex:672
#8  0x00007ffff79f1dd4 in std::call_once<void (*)()>(std::once_flag&, void (*&&)())::{lambda()#2}::operator()() const (this=0x7ffff72ff758) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/mutex:677
#9  0x00007ffff79f1da9 in std::call_once<void (*)()>(std::once_flag&, void (*&&)())::{lambda()#2}::__invoke() () at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/mutex:677
#10 0x00007ffff67c05a7 in __pthread_once_slow () from /lib64/libpthread.so.0
#11 0x00007ffff79ef5eb in __gthread_once (__once=0x7ffff7dd16b0 <Uninitialized>, __func=0x7ffff70085e0 <std::__once_proxy()>) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/x86_64-suse-linux/bits/gthr-default.h:699
#12 0x00007ffff79ef763 in std::call_once<void (*)()> (__once=..., __f=@0x7fffffffc568: 0x7ffff79eec80 <CHIPUninitializeCallOnce()>) at /usr/lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/mutex:684
#13 0x00007ffff79edb73 in CHIPUninitialize () at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPDriver.cc:174
#14 0x00007ffff7a70e4b in __hipUnregisterFatBinary (Data=0x555555e01790) at /gpfs/jlse-fs0/users/pvelesko/CHIP-SPV/src/CHIPBindings.cc:3946
#15 0x00005555555ad24f in __hip_module_dtor ()
#16 0x00007ffff6405b09 in __run_exit_handlers () from /lib64/libc.so.6
#17 0x00007ffff6405c9a in exit () from /lib64/libc.so.6
#18 0x00007ffff63ed2c4 in __libc_start_main () from /lib64/libc.so.6
#19 0x00005555555a4e2a in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by pvelesko** [comment]
Due to creating multiple devices (multi-tile) and then destructor
for plat
for ctx
for dev

destroys the context while the device is still active
