### ISSUE TITLE
i915 Driver Stability Issues

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#330]
- When using iGPU and dGPU, the driver can get into a strange state where any operations will cause Floating Point Exception
- Running tests in parallel causes bus error
- Tests can hang

- [ ] Check if we run tests in parallel when one of the devices is unbound from the driver

Happens upon exit from an OpenCL or Level Zero application after the kernel seems to enter some sort of a corrupt state after  intentionally running Level Zero tests in parallel.

```
Platform #0: Intel(R) FPGA Emulation Platform for OpenCL(TM)
 `-- Device #0: Intel(R) FPGA Emulation Device
Platform #1: Intel(R) OpenCL
 `-- Device #0: 12th Gen Intel(R) Core(TM) i3-12100
Platform #2: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce GTX 1650
Platform #3: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) Graphics [0x56a5]
Platform #4: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) UHD Graphics 730 [0x4692]
Platform #5: AMD Accelerated Parallel Processing
 `-- Device #0: gfx906:sramecc+:xnack-
[1]    467094 floating point exception (core dumped)  clinfo -l
```

```
Thread 1 "clinfo" received signal SIGFPE, Arithmetic exception.
0x00007fffeb998103 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
(gdb) bt
#0  0x00007fffeb998103 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#1  0x00007fffeb937b9b in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#2  0x00007fffeb3773fc in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#3  0x00007fffeb378fdb in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#4  0x00007fffeb3793dd in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#5  0x00007fffeb2f57e9 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#6  0x00005555555647f4 in ?? ()
#7  0x0000555555564a64 in ?? ()
#8  0x0000555555565ee4 in ?? ()
#9  0x0000555555566e38 in ?? ()
#10 0x0000555555567257 in ?? ()
#11 0x000055555555b9b8 in ?? ()
#12 0x00007ffff7d95d90 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x00007ffff7d95e40 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x000055555555be0e in ?? ()
```

I rebooted the machine and now dGPU is now showing up:
```
Platform #0: Intel(R) FPGA Emulation Platform for OpenCL(TM)
 `-- Device #0: Intel(R) FPGA Emulation Device
Platform #1: Intel(R) OpenCL
 `-- Device #0: 12th Gen Intel(R) Core(TM) i3-12100
Platform #2: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce GTX 1650
Platform #3: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) UHD Graphics 730 [0x4692]
Platform #4: AMD Accelerated Parallel Processing
 `-- Device #0: gfx906:sramecc+:xnack-
```

Reboot again and it shows up again:
```
Platform #0: Intel(R) FPGA Emulation Platform for OpenCL(TM)
 `-- Device #0: Intel(R) FPGA Emulation Device
Platform #1: Intel(R) OpenCL
 `-- Device #0: 12th Gen Intel(R) Core(TM) i3-12100
Platform #2: NVIDIA CUDA
 `-- Device #0: NVIDIA GeForce GTX 1650
Platform #3: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) Graphics [0x56a5]
Platform #4: Intel(R) OpenCL HD Graphics
 `-- Device #0: Intel(R) UHD Graphics 730 [0x4692]
Platform #5: AMD Accelerated Parallel Processing
 `-- Device #0: gfx906:sramecc+:xnack-
```

```
➜  ~ sudo dmesg | grep i915
[    6.340207] i915 0000:00:02.0: enabling device (0006 -> 0007)
[    6.340602] i915 0000:00:02.0: [drm] GT count: 1, enabled: 1
[    6.341276] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    6.342527] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
[    6.342876] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adls_dmc_ver2_01.bin (v2.1)
[    6.348189] i915 0000:00:02.0: [drm] GuC firmware i915/tgl_guc_70.5.4.bin version 70.5.4
[    6.348198] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc_7.9.3.bin version 7.9.3
[    6.364520] i915 0000:00:02.0: [drm] HuC authenticated
[    6.364529] i915 0000:00:02.0: [drm] GuC submission disabled
[    6.364532] i915 0000:00:02.0: [drm] GuC SLPC disabled
[    6.365970] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 1
[    6.421541] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    6.422178] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    6.422285] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    6.422426] i915 0000:07:00.0: [drm] GT count: 1, enabled: 1
[    6.423394] i915 0000:07:00.0: [drm] Using Transparent Hugepages
[    6.423447] i915 0000:07:00.0: [drm] Local memory IO size: 0x000000017c800000
[    6.423448] i915 0000:07:00.0: [drm] Local memory available: 0x000000017c800000
[    6.489750] i915 0000:07:00.0: [drm] Finished loading DMC firmware i915/dg2_dmc_ver2_07.bin (v2.7)
[    6.510635] i915 0000:07:00.0: [drm] GuC firmware i915/dg2_guc_70.5.4.bin version 70.5.4
[    6.510641] i915 0000:07:00.0: [drm] HuC firmware i915/dg2_huc_7.10.3_gsc.bin version 7.10.3
[    6.550442] i915 0000:07:00.0: [drm] GuC submission enabled
[    6.550446] i915 0000:07:00.0: [drm] GuC SLPC enabled
[    6.550898] i915 0000:07:00.0: [drm] GuC RC: enabled
[    6.593735] [drm] Initialized i915 1.6.0 20201103 for 0000:07:00.0 on minor 2
[    6.609112] snd_hda_intel 0000:08:00.0: bound 0000:07:00.0 (ops i915_audio_component_bind_ops [i915])
[    6.610956] i915 0000:07:00.0: [drm] Cannot find any crtc or sizes
[    6.611069] i915 0000:07:00.0: [drm] Cannot find any crtc or sizes
[    6.674804] Creating 4 MTD partitions on "i915.spi.1792":
[    6.674808] 0x000000000000-0x000000001000 : "i915.spi.1792.DESCRIPTOR"
[    6.678080] 0x000000001000-0x0000005f0000 : "i915.spi.1792.GSC"
[    6.679079] 0x0000005f0000-0x0000007f0000 : "i915.spi.1792.OptionROM"
[    6.684560] 0x0000007f0000-0x000000800000 : "i915.spi.1792.DAM"
[    7.065236] i915 0000:07:00.0: [drm] HuC authenticated
[    7.065240] mei_pxp i915.mei-gsc.1792-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:07:00.0 (ops i915_pxp_tee_component_ops [i915])
[   13.117563] i915 0000:07:00.0: [drm] *ERROR* Unclaimed access detected prior to suspending
```

**Comment by pvelesko** [comment]
Another driver failure while running unit tests:
```
[    6.353818] i915 0000:00:02.0: enabling device (0006 -> 0007)
[    6.354200] i915 0000:00:02.0: [drm] GT count: 1, enabled: 1
[    6.354870] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    6.355952] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
[    6.357110] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adls_dmc_ver2_01.bin (v2.1)
[    6.361977] i915 0000:00:02.0: [drm] GuC firmware i915/tgl_guc_70.5.4.bin version 70.5.4
[    6.361982] i915 0000:00:02.0: [drm] HuC firmware i915/tgl_huc_7.9.3.bin version 7.9.3
[    6.376238] i915 0000:00:02.0: [drm] HuC authenticated
[    6.376240] i915 0000:00:02.0: [drm] GuC submission disabled
[    6.376241] i915 0000:00:02.0: [drm] GuC SLPC disabled
[    6.377193] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 1
[    6.410694] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    6.411386] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    6.411603] i915 0000:07:00.0: enabling device (0000 -> 0002)
[    6.411621] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    6.411841] i915 0000:07:00.0: [drm] GT count: 1, enabled: 1
[    7.012519] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[    7.012525] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[    7.613313] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[    7.613318] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[    8.214100] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[    8.214103] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[    8.814859] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[    8.814862] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[    9.415624] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[    9.415627] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[    9.415775] i915 0000:07:00.0: [drm] mslice mask all zero!
[   10.016390] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   10.016393] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   10.617142] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   10.617145] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   11.217938] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   11.217943] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   11.818790] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   11.818795] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   12.419629] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   12.419633] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   13.020396] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   13.020399] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   13.621147] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   13.621150] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   14.221883] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   14.221885] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   14.822628] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   14.822631] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   15.423382] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] render: timed out waiting for forcewake ack request.
[   15.423384] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   16.024166] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   16.024167] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   16.025020] i915 0000:07:00.0: [drm] *ERROR* GT0 [ENGINE OTHER] rcs'0.0 reset request timed out: {request: 00000001, RESET_CTL: 00000000}
[   16.025732] i915 0000:07:00.0: [drm] *ERROR* GT0 [ENGINE OTHER] rcs'0.0 reset request timed out: {request: 00000001, RESET_CTL: 00000000}
[   16.026440] i915 0000:07:00.0: [drm] *ERROR* GT0 [ENGINE OTHER] bcs'0.0 reset request timed out: {request: 00000001, RESET_CTL: 00000000}
[   16.026696] i915 0000:07:00.0: [drm] Using Transparent Hugepages
[   16.627327] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   16.627329] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   16.627522] i915 0000:07:00.0: [drm] *ERROR* Failed to setup global region 6 type=3 (-EIO)
[   17.228151] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   17.828877] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   17.828878] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   18.429602] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   18.429604] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   19.030330] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   19.030331] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   19.631043] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   19.631044] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   20.231746] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   20.231747] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   20.832460] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   20.832461] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   21.433165] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   21.433166] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   22.033876] i915 0000:07:00.0: [drm] *ERROR* GT0 [GT OTHER] gt: timed out waiting for forcewake ack request.
[   22.033877] i915 0000:07:00.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by fw_domains_get_with_fallback+0x4ca/0x610 [i915]
[   22.033989] i915 0000:07:00.0: [drm] *ERROR* Failed to setup region(-5) type=1
[   22.312309] i915 0000:07:00.0: Device initialization failed (-5)
[   22.312314] i915 0000:07:00.0: Please contact your Intel representative.
[   22.312317] i915: probe of 0000:07:00.0 failed with error -5
```

**Comment by pvelesko** [comment]
```
#0  0x00007ffff5186dc3 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#1  0x00007ffff5123a3b in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#2  0x00007ffff4d8ad8c in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#3  0x00007ffff4d8b8d8 in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#4  0x00007ffff4d2309b in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#5  0x00007ffff4d8bc2b in ?? () from /lib/x86_64-linux-gnu/libze_intel_gpu.so.1
#6  0x00007ffff7a5d5ae in zeCommandListDestroy () from /usr/local/lib/libze_loader.so.1
#7  0x00007ffff7ecf20f in CHIPStaleEventMonitorLevel0::monitor (this=0x5555559008d0) at /home/pvelesko/CHIP-SPV/chip-spv/src/backend/Level0/CHIPBackendLevel0.cc:680
#8  0x00007ffff7eafa0e in CHIPEventMonitor::monitorWrapper (Arg=0x5555559008d0) at /home/pvelesko/CHIP-SPV/chip-spv/src/CHIPBackend.hh:322
#9  0x00007ffff7550b43 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007ffff75e2a00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) Quit
```

**Comment by pvelesko** [comment]
I narrowed it down to having two devices on the i915 module. If I unbind one or the other then I stop getting the floating point exception.

**Comment by pvelesko** [comment]
@pengtu closing this ticket but tagging you here in case these notes might be useful to the driver team. 

Current solution is to bind/unbind iGPU or dGPU from the i915 driver as having two of them bound to the driver causes errors.

**Comment by pvelesko** [comment]
@pengtu I just updated the driver and can confirm that these issues have been resolved. I can now run two devices on the same driver without any issues and dGPU name is displayed correctly.
