### ISSUE TITLE
Devicelib failures on CPU OpenCL Intel Compute Runtime + Release Build

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#410]
- [ ] Create a reproducer to check if the same failing test passes without Catch2

```
Thread 1 "__cosf" received signal SIGSEGV, Segmentation fault.
0x00007fffe98d5ad9 in llvm::Attribute::canUseAsParamAttr(llvm::Attribute::AttrKind) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
(gdb) bt
#0  0x00007fffe98d5ad9 in llvm::Attribute::canUseAsParamAttr(llvm::Attribute::AttrKind) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#1  0x00007fffe9a5d473 in (anonymous namespace)::Verifier::verifyParameterAttrs(llvm::AttributeSet, llvm::Type*, llvm::Value const*) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#2  0x00007fffe9a5ab52 in (anonymous namespace)::Verifier::verifyFunctionAttrs(llvm::FunctionType*, llvm::AttributeList, llvm::Value const*, bool, bool) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#3  0x00007fffe9a582b0 in llvm::InstVisitor<(anonymous namespace)::Verifier, void>::visit(llvm::Function&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#4  0x00007fffe9a502a5 in (anonymous namespace)::Verifier::verify(llvm::Function const&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#5  0x00007fffe9a519f3 in llvm::verifyModule(llvm::Module const&, llvm::raw_ostream*, bool*) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#6  0x00007fffe92c3594 in SPIRV::SPIRVToOCL12Base::runSPIRVToOCL(llvm::Module&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#7  0x00007fffe92c2aa2 in llvm::detail::PassModel<llvm::Module, SPIRV::SPIRVToOCL12Pass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#8  0x00007fffe9a2d87c in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#9  0x00007fffe926ac96 in llvm::convertSpirvToLLVM(llvm::LLVMContext&, SPIRV::SPIRVModule&, SPIRV::TranslatorOpts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#10 0x00007fffe926be50 in llvm::readSpirv(llvm::LLVMContext&, SPIRV::TranslatorOpts const&, std::istream&, llvm::Module*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#11 0x00007fffe9093bb5 in Intel::OpenCL::ClangFE::ClangFECompilerParseSPIRVTask::ParseSPIRV(Intel::OpenCL::ClangFE::IOCLFEBinaryResult**) () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#12 0x00007fffe908ab52 in Intel::OpenCL::ClangFE::ClangFECompiler::ParseSPIRV(Intel::OpenCL::FECompilerAPI::FESPIRVProgramDescriptor*, Intel::OpenCL::ClangFE::IOCLFEBinaryResult**) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libclang_compiler.so.2022.15.12.0
#13 0x00007ffff74f5c0a in Intel::OpenCL::Framework::FrontEndCompiler::ParseSpirv(char const*, unsigned int, char const*, unsigned long, unsigned int const*, unsigned long const*, char**, unsigned long*, char**) const ()
   from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#14 0x00007ffff74aec03 in Intel::OpenCL::Framework::CompileTask::Execute() () from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#15 0x00007ffff74af05d in non-virtual thunk to Intel::OpenCL::Framework::CompileTask::Execute() () from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#16 0x00007ffff71161de in Intel::OpenCL::TaskExecutor::execute_command(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&, Intel::OpenCL::TaskExecutor::base_command_list&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libtask_executor.so.2022.15.12.0
#17 0x00007ffff710296a in tbb::detail::d1::task_arena_function<Intel::OpenCL::TaskExecutor::immediate_executor_task, void>::operator()() const () from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libtask_executor.so.2022.15.12.0
#18 0x00007ffff68121b0 in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...)
    at /localdisk/ci/runner001/intel-innersource/001/_work/libraries.threading.infrastructure.onetbb-ci/libraries.threading.infrastructure.onetbb-ci/onetbb_source_code/src/tbb/arena.cpp:694
#19 0x00007ffff7101233 in Intel::OpenCL::TaskExecutor::immediate_command_list::LaunchExecutorTask(bool, Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&) ()
   from /opt/intel/oneapi/compiler/2023.0.0/linux/lib/x64/libtask_executor.so.2022.15.12.0
#20 0x00007ffff7462dc6 in Intel::OpenCL::Framework::FrameworkProxy::ExecuteImmediate(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::TaskExecutor::ITaskBase> const&) const () from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#21 0x00007ffff74ae0ae in Intel::OpenCL::Framework::BuildTask::Launch() () from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#22 0x00007ffff74b9d52 in Intel::OpenCL::Framework::ProgramService::BuildProgram(Intel::OpenCL::Utils::SharedPtr<Intel::OpenCL::Framework::Program>&, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) ()
   from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#23 0x00007ffff749095a in Intel::OpenCL::Framework::Context::BuildProgram(_cl_program*, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) ()
   from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#24 0x00007ffff7473a39 in Intel::OpenCL::Framework::ContextModule::BuildProgram(_cl_program*, unsigned int, _cl_device_id* const*, char const*, void (*)(_cl_program*, void*), void*) ()
   from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#25 0x00007ffff741e60c in clBuildProgram () from /opt/intel/oneapi/compiler/latest/linux/lib/x64/libintelocl.so
#26 0x00007ffff78ab01f in clBuildProgram (program=0x55555679b358, num_devices=0, device_list=0x0, options=0x5555567e16e0 "-x spir -cl-kernel-arg-info", pfn_notify=0x0, user_data=0x0) at ocl_icd_loader_gen.c:2072
#27 0x00007ffff7f493e0 in cl::Program::build (this=this@entry=0x7fffffffb658, options=0x2 <error: Cannot access memory at address 0x2>, notifyFptr=0x7fffffff7c90, notifyFptr@entry=0x0, data=0x7fffffff8840, data@entry=0x0)
    at /home/pvelesko/CHIP-SPV/main/include/CL/opencl.hpp:6709
#28 0x00007ffff7f3c53b in CHIPModuleOpenCL::compile (this=0x5555567d8880, ChipDev=0x5555567c2340) at /home/pvelesko/CHIP-SPV/main/src/backend/OpenCL/CHIPBackendOpenCL.cc:675
#29 0x00007ffff7f4abef in CHIPDeviceOpenCL::compile (this=0x5555567c2340, SrcMod=...) at /home/pvelesko/CHIP-SPV/main/src/backend/OpenCL/CHIPBackendOpenCL.hh:192
#30 0x00007ffff7ed0402 in CHIPDevice::getOrCreateModule (this=0x5555567c2340, this@entry=0x7fffffffbcd0, SrcMod=...) at /home/pvelesko/CHIP-SPV/main/src/CHIPBackend.cc:995
#31 0x00007ffff7ed00d3 in CHIPDevice::getOrCreateModule (this=0xffffffff, Ptr=...) at /home/pvelesko/CHIP-SPV/main/src/CHIPBackend.cc:969
#32 0x00007ffff7ecff3d in CHIPDevice::prepareDeviceVariables (this=0xffffffff, Ptr=...) at /home/pvelesko/CHIP-SPV/main/src/CHIPBackend.cc:929
#33 0x00007ffff7f1688b in hipLaunchKernel (HostFunction=0x55555560be40 <testKernel___cosf(float*)>, GridDim=..., BlockDim=..., Args=0x7fffffffbcd0, SharedMem=<optimized out>, Stream=<optimized out>)
    at /home/pvelesko/CHIP-SPV/main/src/CHIPBindings.cc:3701
#34 0x000055555556e570 in ____C_A_T_C_H____T_E_S_T____17 () at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/unit/deviceLib/SinglePrecisionIntrinsics/__cosf.cc:2
#35 0x0000555555583f29 in Catch::TestCase::invoke (this=<optimized out>) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:14100
#36 Catch::RunContext::invokeActiveTestCase (this=0x7fffffffc220) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:12959
#37 Catch::RunContext::runCurrentTest (this=this@entry=0x7fffffffc220, redirectedCout=..., redirectedCerr=...) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:12932
#38 0x00005555555835bf in Catch::RunContext::runTest (this=this@entry=0x7fffffffc220, testCase=...) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:12693
#39 0x00005555555885d9 in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffc210) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:13287
#40 Catch::Session::runInternal (this=this@entry=0x7fffffffc4b0) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:13493
#41 0x0000555555587815 in Catch::Session::run (this=this@entry=0x7fffffffc4b0) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:13449
#42 0x000055555559cca2 in Catch::Session::run<char> (this=0x7fffffffc4b0, argc=<optimized out>, argv=<optimized out>) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:13171
#43 main (argc=1, argv=0x7fffffffc768) at /home/pvelesko/CHIP-SPV/main/HIP/tests/catch/external/Catch2/catch.hpp:17448
```

**Comment by pvelesko** [comment]
iirc this is affected by Catch2.
