### ISSUE TITLE
PoCL + LLVM16 + Patched SPIR-V Translator Tool Failures

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#414]
These two types of failures now observed on the CI machine. These tests pass on Intel OpenCL

         41 - sharedMemory (SEGFAULT)
         49 - stream (SEGFAULT)
         52 - deviceManagement (SEGFAULT)
         82 - cuda-matrixMul (SEGFAULT)
```
Thread 9 "deviceManagemen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe6ffd640 (LWP 2211039)]
0x00007fffec12f352 in _pocl_kernel__Z15matrixTransposePfS_i_workgroup () from /home/pvelesko/.cache/pocl/kcache/CO/HICNGDHNMLAPHIFCPODFLFECMOKFDCCKCBAMO/_Z15matrixTransposePfS_i/4-4-1-goffs0-smallgrid/_Z15matrixTransposePfS_i.so
(gdb) bt
#0  0x00007fffec12f352 in _pocl_kernel__Z15matrixTransposePfS_i_workgroup () from /home/pvelesko/.cache/pocl/kcache/CO/HICNGDHNMLAPHIFCPODFLFECMOKFDCCKCBAMO/_Z15matrixTransposePfS_i/4-4-1-goffs0-smallgrid/_Z15matrixTransposePfS_i.so
#1  0x0000000000000000 in ?? ()
```

        784 - Unit_hipTextureFetch_vector (Failed)
        785 - Unit_hipTextureObj2D_Check (Failed)
        787 - Unit_hipCreateTextureObject_tex1DfetchVerification (Failed)
        788 - Unit_hipTextureObj1DCheckModes (Failed)
        789 - Unit_hipTextureObj2DCheckModes (Failed)
```
1164: Test command: /home/pvelesko/CHIP-SPV/pocl-clang16-ci/build_llvm16debug/catch/catch_tests/unit/texture/hipTextureObjFetchVector "Unit_hipTextureFetch_vector"
1164: Test timeout computed to be: 10000000
1164: PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
1164: Stack dump:
1164: 0.	Program arguments: /home/pvelesko/install/clang/16.0/bin/llvm-spirv --spirv-target-env=CL1.2 -r -o /home/pvelesko/.cache/pocl/kcache/tempfile_1xMZsu.bc /home/pvelesko/.cache/pocl/kcache/tempfile_NDM2zM.spirv
1164:  #0 0x00007f6c46e8f5f2 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/pvelesko/install/clang/16.0/lib/libLLVMSupport.so.16+0x1bd5f2)
1164:  #1 0x00007f6c46e8ce1b SignalHandler(int) Signals.cpp:0:0
1164:  #2 0x00007f6c468ad520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
1164:  #3 0x00007f6c471520f2 llvm::CallInst::init(llvm::FunctionType*, llvm::Value*, llvm::ArrayRef<llvm::Value*>, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*>>, llvm::Twine const&) (/home/pvelesko/install/clang/16.0/lib/libLLVMCore.so.16+0x2190f2)
1164:  #4 0x00007f6c476314dc SPIRV::addCallInst(llvm::Module*, llvm::StringRef, llvm::Type*, llvm::ArrayRef<llvm::Value*>, llvm::AttributeList*, llvm::Instruction*, SPIRV::BuiltinFuncMangleInfo*, llvm::StringRef, bool) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x2044dc)
1164:  #5 0x00007f6c4758e21e SPIRV::BuiltinCallMutator::doConversion() (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x16121e)
1164:  #6 0x00007f6c475572f3 SPIRV::BuiltinCallMutator::~BuiltinCallMutator() (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x12a2f3)
1164:  #7 0x00007f6c475fb1ad SPIRV::SPIRVToOCLBase::visitCallSPIRVImageSampleExplicitLodBuiltIn(llvm::CallInst*, spv::Op) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1ce1ad)
1164:  #8 0x00007f6c47602486 SPIRV::SPIRVToOCLBase::visitCallInst(llvm::CallInst&) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1d5486)
1164:  #9 0x00007f6c47603515 SPIRV::SPIRVToOCL12Base::runSPIRVToOCL(llvm::Module&) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1d6515)
1164: #10 0x00007f6c475f6e14 llvm::detail::PassModel<llvm::Module, SPIRV::SPIRVToOCL12Pass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1c9e14)
1164: #11 0x00007f6c475e2f3d llvm::convertSpirvToLLVM(llvm::LLVMContext&, SPIRV::SPIRVModule&, SPIRV::TranslatorOpts const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1b5f3d)
1164: #12 0x00007f6c475e3534 llvm::readSpirv(llvm::LLVMContext&, SPIRV::TranslatorOpts const&, std::istream&, llvm::Module*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>&) (/home/pvelesko/install/clang/16.0/lib/libLLVMSPIRVLib.so.16+0x1b6534)
1164: #13 0x0000556c00f3fc3d main (/home/pvelesko/install/clang/16.0/bin/llvm-spirv+0x9c3d)
1164: #14 0x00007f6c46894d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
1164: #15 0x00007f6c46894e40 call_init ./csu/../csu/libc-start.c:128:20
1164: #16 0x00007f6c46894e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
1164: #17 0x0000556c00f40b25 _start (/home/pvelesko/install/clang/16.0/bin/llvm-spirv+0xab25)
1164: CHIP error [TID 2193544] [1682232823.528339557] : Program BUILD LOG for device #0:pthread-12th Gen Intel(R) Core(TM) i3-12100:
1164: Device pthread-12th Gen Intel(R) Core(TM) i3-12100 failed to build the program
```

**Comment by pjaaskel** [comment]
The above set of tests should now work on the latest PoCL rev. Are the texture tests supposed to work, have they worked at some point? I recall the texture implementation is not complete.

**Comment by pvelesko** [comment]
> The above set of tests should now work on the latest PoCL rev
I'll try that today

> Are the texture tests supposed to work, have they worked at some point? I recall the texture implementation is not complete.

yes, these are new failures. Either way, compiler crash is not desired.

**Comment by pvelesko** [comment]
The texture tests are failing for Intel CPU as well, @pjaaskel

**Comment by pvelesko** [comment]
PoCL update resolved these:
```
     41 - sharedMemory (SEGFAULT)
     49 - stream (SEGFAULT)
     52 - deviceManagement (SEGFAULT)
     82 - cuda-matrixMul (SEGFAULT)
```

**Comment by linehill** [comment]
Most likely related to: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2008.

**Comment by pvelesko** [comment]
Is the source of this error likely the same for both Intel and PoCL? Do I need to do anything else in regards to this ticket?

**Comment by pjaaskel** [comment]
This might have to do with a SPIRV-Translator issue we today observed with LLVM 16-produced IR related to images and samplers (related to the opaque pointers transition). https://github.com/pocl/pocl/issues/1232  https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2008

**Comment by linehill** [comment]
Dropped from Milestone 1.0: resolution depends on external issue.
