### ISSUE TITLE
[rocprim] test_block_radix_rank makes the kernel compiler fail without output 

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#453]
This started happening some time ago (perhaps after a driver update) here with Intel iGPU:
```
#0  __GI_exit (status=1) at ./stdlib/exit.c:142
#1  0x00007fffc44d3c8a in ?? () from /usr/local/lib/libigc.so.1
#2  0x00007fffc44d948d in ?? () from /usr/local/lib/libigc.so.1
#3  0x00007fffc44dbc85 in ?? () from /usr/local/lib/libigc.so.1
#4  0x00007fffc4deadca in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /usr/local/lib/libigc.so.1
#5  0x00007fffc4dec359 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /usr/local/lib/libigc.so.1
#6  0x00007fffc4dea0b1 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/local/lib/libigc.so.1
#7  0x00007fffc4200af9 in ?? () from /usr/local/lib/libigc.so.1
#8  0x00007fffc3fed227 in ?? () from /usr/local/lib/libigc.so.1
#9  0x00007fffc416bb3b in ?? () from /usr/local/lib/libigc.so.1
#10 0x00007fffc3fef1bb in ?? () from /usr/local/lib/libigc.so.1
#11 0x00007fffc4117572 in ?? () from /usr/local/lib/libigc.so.1
#12 0x00007ffff6977d2f in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#13 0x00007ffff65194fa in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#14 0x00007ffff64bcfb3 in ?? () from /usr/lib/x86_64-linux-gnu/intel-opencl/libigdrcl.so
#15 0x00007ffff7f31100 in cl::Program::build (this=this@entry=0x7fffffffd270, options=0x55555b0a7af8 "\220\370\374YUU", notifyFptr=0x1, 
    notifyFptr@entry=0x0, data=0x555559fcf950, data@entry=0x0) at /home/pjaaskel/src/chip-spv/include/CL/opencl.hpp:6709
#16 0x00007ffff7f20a22 in CHIPModuleOpenCL::compile (this=0x555559d6b970, ChipDev=0x55555807f530)
    at /home/pjaaskel/src/chip-spv/src/backend/OpenCL/CHIPBackendOpenCL.cc:745
#17 0x00007ffff7f32b5f in CHIPDeviceOpenCL::compile (this=0x55555807f530, SrcMod=...)
    at /home/pjaaskel/src/chip-spv/src/backend/OpenCL/CHIPBackendOpenCL.hh:206
#18 0x00007ffff7ead686 in CHIPDevice::getOrCreateModule (this=0x55555807f530, this@entry=0x7fffffffd920, SrcMod=...)
    at /home/pjaaskel/src/chip-spv/src/CHIPBackend.cc:980
#19 0x00007ffff7eac926 in CHIPDevice::getOrCreateModule (this=0x1, Ptr=...) at /home/pjaaskel/src/chip-spv/src/CHIPBackend.cc:954
#20 0x00007ffff7eac70d in CHIPDevice::prepareDeviceVariables (this=0x1, Ptr=...) at /home/pjaaskel/src/chip-spv/src/CHIPBackend.cc:914
#21 0x00007ffff7ef85cb in hipLaunchKernel 
```

The driver just calls exit(1) at some point, stopping the test early. 
Reproduces with the latest compute-runtime (v23.13.26032.30).

Reproduces with PoCL-CPU (LLVM 15) with an LLVM assertion outputted:

```
test_block_radix_rank: /home/pjaaskel/src/llvm-project/llvm/lib/IR/Value.cpp:502: void llvm::Value::doRAUW(llvm::Value*, llvm::Value::ReplaceMetadataUses): Assertion `New->getType() == getType() && "replaceAllUses of value with new value of different type!"' failed.
```

PoCL-CPU with LLVM 16 fails as follows:

```
Error(s) while linking: 
Function return type does not match operand type of return inst!
  ret i64 %call
i32<unknown>:0:0: SLP vectorized with cost -1 and with tree size 5<unknown>:0:0: SLP vectorized with cost -1 and with tree size 5<unknown>:0:0: loop not vectorized: control flow cannot be substituted for a select<unknown>:0:0: loop not vectorized: instruction return type cannot be vectorized<unknown>:0:0: loop not vectorized: control flow cannot be substituted for a select<unknown>:0:0: loop not vectorized: instruction return type cannot be vectorized<unknown>:0:0: loop not vectorized: control flow cannot be substituted for a select<unknown>:0:0: loop not vectorized: instruction return type cannot be vectorized<unknown>:0:0: loop not vectorized: control flow cannot be substituted for a select<unknown>:0:0: loop not vectorized: instruction return type cannot be vectorized<unknown>:0:0: 1509 instructions in function<unknown>:0:0: 1452 instructions in function<unknown>:0:0: SLP vectorized with cost -1 and with tree size 5<unknown>:0:0: SLP vectorized with cost -1 and with tree size 5<unknown>:0:0: loop not vectorized:
...
```

Intel CPU OpenCL runs the test fine.

**Comment by pjaaskel** [comment]
Perhaps because now we call the clang builtin which returns int for ulong inputs too:
```
Built-in Function: int __builtin_popcountl (unsigned long)

    Similar to __builtin_popcount, except the argument type is unsigned long. 
```
https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

If we don't want to modify the ROCm-Device-Libs I think we need to have to fix the declaration and all calls to it in our own pass or in SPIR-V-Translator.

**Comment by pjaaskel** [comment]
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/issues/2023 - not sure what the best solution here is. Maybe CHIP-SPV LLVM pass to tackle these corner cases before going to SPIRV translator...
